= mDNS

include::./includes/attributes.adoc[]

A Quarkus extension allowing use of Multicast DNS or `mDNS` to expose service advertisement as well as discover other services on your network.

mDNS is sometimes also called ZeroConf/Bonjour/Avahi/Rendezvous and can work in conjunction with DNS Service Discovery (DNS-SD), a companion zero-configuration networking technique specified separately in RFC 6763.

== Installation

If you want to use this extension, you need to add the `io.quarkiverse.mdns:quarkus-mdns` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.mdns</groupId>
    <artifactId>quarkus-mdns</artifactId>
    <version>{project-version}</version>
</dependency>
----

== Service Advertisement

`mDNS` by default will advertise your Quarkus server for HTTP discovery.

[source,properties]
----
quarkus.http.port=8081
quarkus.application.name=integration
----

Will expose your server on mDNS as `http://myserver:8081` as an HTTP service type `_http._tcp.local.`.

Or you can inject it manually and expose any service you like. For example, this would expose it as supporting Apple TouchRemote on port 1024.

[source,java]
----
@Inject
JmDNS jmdns;

public void advertise() {
    Map<String, String> props = new HashMap<>();
    props.put("DvNm", "Quarkus Client");
    props.put("RemV", "10000");
    props.put("DvTy", "iPod");
    props.put("RemN", "Remote");
    props.put("txtvers", "1");
    ServiceInfo serviceInfo = ServiceInfo.create("_touch-remote._tcp", hostName, 1024, 0, 0, props);
    jmdns.registerService(serviceInfo);
}
----

== Service Discovery

You may also use `mDNS` to discover other services on your network by using the injectable component.  For example if you wanted to discover all the Apple Airport `_airport._tcp.local.` devices on your local network.

[source,java]
----
@Inject
JmDNS jmdns;

public void listServices() {
    ServiceInfo[] infos = jmdns.list("_airport._tcp.local.");
    for (ServiceInfo info : infos) {
        System.out.println(info);
    }
}
----

Will expose your server on mDNS as `http://myserver:8081` as an HTTP service type `_http._tcp.local.`.



[[extension-configuration-reference]]
== Extension Configuration Reference

include::includes/quarkus-mdns.adoc[leveloffset=+1, opts=optional]